---
# tasks file for check_cmsp_state
- name: Get current CMSP configuration
  ansible.builtin.uri:
    url: "https://{{ nutanix_host }}:{{ nutanix_port }}/PrismGateway/services/rest/v1/genesis"
    body:
      value: '{".oid":"ClusterManager",".method":"get_cmsp_status",".kwargs":{}}'
    method: POST
    validate_certs: "{{ validate_certs }}"
    body_format: json
    status_code: 200
    headers:
      Authorization: "{{ nutanix_api_auth }}"
  register: nutanix_cmsp_current_state

- name: Debug nutanix_cmsp_current_state
  ansible.builtin.debug:
    var: nutanix_cmsp_current_state
  when:
    - nutanix_debug

- name: Set nutanix_cmsp_current_state_result_value
  ansible.builtin.set_fact:
    nutanix_cmsp_current_state_result_value: "{{ nutanix_cmsp_current_state.json | community.general.json_query(query) | to_json | from_json }}"
  vars:
    query: "value"

- name: Debug nutanix_cmsp_current_state_result_value
  ansible.builtin.debug:
    var: nutanix_cmsp_current_state_result_value
  when:
    - nutanix_debug

- name: Set nutanix_cmsp_current_state
  ansible.builtin.set_fact:
    nutanix_cmsp_current_state: '{{ nutanix_cmsp_current_state_result_value[".return"]["status"] }}'
  vars:
    query: 'value.".return".status'

- name: Debug nutanix_cmsp_current_state
  ansible.builtin.debug:
    var: nutanix_cmsp_current_state
  when:
    - nutanix_debug

- name: Set nutanix_cmsp_current_task_uuid
  ansible.builtin.set_fact:
    nutanix_cmsp_current_task_uuid: '{{ nutanix_cmsp_current_state_result_value[".return"]["enable_task"] }}'
  vars:
    query: 'value.".return".status'

- name: Debug nutanix_cmsp_current_task_uuid
  ansible.builtin.debug:
    var: nutanix_cmsp_current_task_uuid
  when:
    - nutanix_debug
