---
# tasks file for check_cmsp_state
- name: Get current CMSP configuration
  ansible.builtin.uri:
    url: "https://{{ role_nutanix_prism_api_url_base }}/PrismGateway/services/rest/v1/genesis"
    body:
      value: '{".oid":"ClusterManager",".method":"get_cmsp_status",".kwargs":{}}'
    method: POST
    validate_certs: "{{ role_nutanix_pc_svc_cmsp_host_validate_certs }}"
    body_format: json
    status_code: 200
    headers:
      Authorization: "{{ role_nutanix_prism_api_auth_string_b64 }}"
  register: role_nutanix_pc_svc_cmsp_current_state

- name: Debug role_nutanix_pc_svc_cmsp_current_state
  ansible.builtin.debug:
    var: role_nutanix_pc_svc_cmsp_current_state
  when:
    - role_nutanix_pc_svc_cmsp_debug

- name: Set role_nutanix_pc_svc_cmsp_current_state_result_value
  ansible.builtin.set_fact:
    role_nutanix_pc_svc_cmsp_current_state_result_value: >-
      "{{ role_nutanix_pc_svc_cmsp_current_state.json
      | community.general.json_query(query)
      | to_json
      | from_json }}"
  vars:
    query: "value"

- name: Debug role_nutanix_pc_svc_cmsp_current_state_result_value
  ansible.builtin.debug:
    var: role_nutanix_pc_svc_cmsp_current_state_result_value
  when:
    - role_nutanix_pc_svc_cmsp_debug

- name: Set role_nutanix_pc_svc_cmsp_current_state
  ansible.builtin.set_fact:
    role_nutanix_pc_svc_cmsp_current_state: '{{ role_nutanix_pc_svc_cmsp_current_state_result_value[".return"]["status"] }}'
  vars:
    query: 'value.".return".status'

- name: Debug role_nutanix_pc_svc_cmsp_current_state
  ansible.builtin.debug:
    var: role_nutanix_pc_svc_cmsp_current_state
  when:
    - role_nutanix_pc_svc_cmsp_debug

- name: Set role_nutanix_pc_svc_cmsp_task_uuid
  ansible.builtin.set_fact:
    role_nutanix_pc_svc_cmsp_task_uuid: '{{ role_nutanix_pc_svc_cmsp_current_state_result_value[".return"]["enable_task"] }}'
  vars:
    query: 'value.".return".status'

- name: Debug role_nutanix_pc_svc_cmsp_task_uuid
  ansible.builtin.debug:
    var: role_nutanix_pc_svc_cmsp_task_uuid
  when:
    - role_nutanix_pc_svc_cmsp_debug
